# Titanic survival analysis- Project

# By- Srishti Chopra

In [1]:
import numpy as np
import pandas as pd

In [2]:
training_data_raw= pd.read_csv('train.csv')

In [3]:
training_data_raw.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
test_data=pd.read_csv('test.csv')

In [5]:
test_data.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [6]:
training_data_raw.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
training_data_raw.describe(include='all')

PassengerId    Survived      Pclass                     Name   Sex  \
count    891.000000  891.000000  891.000000                      891   891   
unique          NaN         NaN         NaN                      891     2   
top             NaN         NaN         NaN  Braund, Mr. Owen Harris  male   
freq            NaN         NaN         NaN                        1   577   
mean     446.000000    0.383838    2.308642                      NaN   NaN   
std      257.353842    0.486592    0.836071                      NaN   NaN   
min        1.000000    0.000000    1.000000                      NaN   NaN   
25%      223.500000    0.000000    2.000000                      NaN   NaN   
50%      446.000000    0.000000    3.000000                      NaN   NaN   
75%      668.500000    1.000000    3.000000                      NaN   NaN   
max      891.000000    1.000000    3.000000                      NaN   NaN   

               Age       SibSp       Parch  Ticket        Fare    Cabin  \
count   714.000000  891.000000  891.000000     891  891.000000      204   
unique         NaN         NaN         NaN     681         NaN      147   
top            NaN         NaN         NaN  347082         NaN  B96 B98   
freq           NaN         NaN         NaN       7         NaN        4   
mean     29.699118    0.523008    0.381594     NaN   32.204208      NaN   
std      14.526497    1.102743    0.806057     NaN   49.693429      NaN   
min       0.420000    0.000000    0.000000     NaN    0.000000      NaN   
25%      20.125000    0.000000    0.000000     NaN    7.910400      NaN   
50%      28.000000    0.000000    0.000000     NaN   14.454200      NaN   
75%      38.000000    1.000000    0.000000     NaN   31.000000      NaN   
max      80.000000    8.000000    6.000000     NaN  512.329200      NaN   

       Embarked  
count       889  
unique        3  
top           S  
freq        644  
mean        NaN  
std         NaN  
min         NaN  
25%         NaN  
50%         NaN  
75%         NaN  
max         NaN

In [8]:
training_data_raw= training_data_raw.drop(['Cabin'],axis=1)
training_data_raw.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  
0      0         A/5 21171   7.2500        S  
1      0          PC 17599  71.2833        C  
2      0  STON/O2. 3101282   7.9250        S  
3      0            113803  53.1000        S  
4      0            373450   8.0500        S

In [9]:
training_data_raw['Age'].fillna(training_data_raw['Age'].mean(), inplace=True)

In [10]:
training_data_raw.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [11]:
print(training_data_raw['Embarked'].mode())

0    S
dtype: object


In [12]:
training_data_raw['Embarked'].fillna(training_data_raw['Embarked'].mode()[0], inplace=True)

In [13]:
training_data_raw.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [14]:
training_data_raw=training_data_raw.drop(['PassengerId'],axis=1)

In [15]:
training_data_raw.head()

Survived  Pclass                                               Name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   

      Sex   Age  SibSp  Parch            Ticket     Fare Embarked  
0    male  22.0      1      0         A/5 21171   7.2500        S  
1  female  38.0      1      0          PC 17599  71.2833        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250        S  
3  female  35.0      1      0            113803  53.1000        S  
4    male  35.0      0      0            373450   8.0500        S

In [16]:
training_data_raw=training_data_raw.drop(['Name'],axis=1)
training_data_raw.head()

Survived  Pclass     Sex   Age  SibSp  Parch            Ticket     Fare  \
0         0       3    male  22.0      1      0         A/5 21171   7.2500   
1         1       1  female  38.0      1      0          PC 17599  71.2833   
2         1       3  female  26.0      0      0  STON/O2. 3101282   7.9250   
3         1       1  female  35.0      1      0            113803  53.1000   
4         0       3    male  35.0      0      0            373450   8.0500   

  Embarked  
0        S  
1        C  
2        S  
3        S  
4        S

In [17]:
training_data_raw.replace({'Sex':{'male':0,'female':1}, 'Embarked':{'S':0,'C':1,'Q':2}}, inplace=True)
training_data_raw.head()

Survived  Pclass  Sex   Age  SibSp  Parch            Ticket     Fare  \
0         0       3    0  22.0      1      0         A/5 21171   7.2500   
1         1       1    1  38.0      1      0          PC 17599  71.2833   
2         1       3    1  26.0      0      0  STON/O2. 3101282   7.9250   
3         1       1    1  35.0      1      0            113803  53.1000   
4         0       3    0  35.0      0      0            373450   8.0500   

   Embarked  
0         0  
1         1  
2         0  
3         0  
4         0

In [18]:
training_data_raw['Ticket'].unique()

array(['A/5 21171', 'PC 17599', 'STON/O2. 3101282', '113803', '373450',
       '330877', '17463', '349909', '347742', '237736', 'PP 9549',
       '113783', 'A/5. 2151', '347082', '350406', '248706', '382652',
       '244373', '345763', '2649', '239865', '248698', '330923', '113788',
       '347077', '2631', '19950', '330959', '349216', 'PC 17601',
       'PC 17569', '335677', 'C.A. 24579', 'PC 17604', '113789', '2677',
       'A./5. 2152', '345764', '2651', '7546', '11668', '349253',
       'SC/Paris 2123', '330958', 'S.C./A.4. 23567', '370371', '14311',
       '2662', '349237', '3101295', 'A/4. 39886', 'PC 17572', '2926',
       '113509', '19947', 'C.A. 31026', '2697', 'C.A. 34651', 'CA 2144',
       '2669', '113572', '36973', '347088', 'PC 17605', '2661',
       'C.A. 29395', 'S.P. 3464', '3101281', '315151', 'C.A. 33111',
       'S.O.C. 14879', '2680', '1601', '348123', '349208', '374746',
       '248738', '364516', '345767', '345779', '330932', '113059',
       'SO/C 14885', '31012

In [19]:
training_data_raw=training_data_raw.drop(['Ticket'],axis=1)
training_data_raw.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    0  22.0      1      0   7.2500         0
1         1       1    1  38.0      1      0  71.2833         1
2         1       3    1  26.0      0      0   7.9250         0
3         1       1    1  35.0      1      0  53.1000         0
4         0       3    0  35.0      0      0   8.0500         0

In [20]:
training_data_raw['Pclass'].unique()

array([3, 1, 2], dtype=int64)

In [21]:
training_data_raw['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [22]:
training_data_raw['Parch'].unique()

array([0, 1, 2, 5, 3, 4, 6], dtype=int64)

In [23]:
training_data_raw['Fare'].unique()

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
        31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,  18.    ,
         7.225 ,  26.    ,   8.0292,  35.5   ,  31.3875, 263.    ,
         7.8792,   7.8958,  27.7208, 146.5208,   7.75  ,  10.5   ,
        82.1708,  52.    ,   7.2292,  11.2417,   9.475 ,  21.    ,
        41.5792,  15.5   ,  21.6792,  17.8   ,  39.6875,   7.8   ,
        76.7292,  61.9792,  27.75  ,  46.9   ,  80.    ,  83.475 ,
        27.9   ,  15.2458,   8.1583,   8.6625,  73.5   ,  14.4542,
        56.4958,   7.65  ,  29.    ,  12.475 ,   9.    ,   9.5   ,
         7.7875,  47.1   ,  15.85  ,  34.375 ,  61.175 ,  20.575 ,
        34.6542,  63.3583,  23.    ,  77.2875,   8.6542,   7.775 ,
        24.15  ,   9.825 ,  14.4583, 247.5208,   7.1417,  22.3583,
         6.975 ,   7.05  ,  14.5   ,  15.0458,  26.2833,   9.2167,
        79.2   ,   6.75  ,  11.5   ,  36.75  ,   7.7958,  12.5

In [24]:
training_data_raw['Survived'].sum()/training_data_raw.shape[0]

0.3838383838383838

In [25]:
#The number of people survived is around 38%
#This means the data set used for training is imbalanced
#This might lead to the algorithm misbehaving
#Thus, we need to balance the dataset

In [26]:
targets_all=training_data_raw['Survived']
targets_all

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [27]:
inputs=training_data_raw.drop(['Survived'],axis=1)
inputs

Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
0         3    0  22.000000      1      0   7.2500         0
1         1    1  38.000000      1      0  71.2833         1
2         3    1  26.000000      0      0   7.9250         0
3         1    1  35.000000      1      0  53.1000         0
4         3    0  35.000000      0      0   8.0500         0
..      ...  ...        ...    ...    ...      ...       ...
886       2    0  27.000000      0      0  13.0000         0
887       1    1  19.000000      0      0  30.0000         0
888       3    1  29.699118      1      2  23.4500         0
889       1    0  26.000000      0      0  30.0000         1
890       3    0  32.000000      0      0   7.7500         2

[891 rows x 7 columns]

In [28]:
type(inputs)

pandas.core.frame.DataFrame

In [29]:
type(targets_all)

pandas.core.series.Series

In [30]:
targets_all.shape[0]

891

In [31]:
num_one_targets = int(np.sum(targets_all))
num_one_targets

342

In [32]:
891-342

549

In [33]:
num_one_targets = int(np.sum(targets_all))
zero_targets_counter = 0

indices_to_remove = []
for i in range(891):
    if targets_all[i] == 0:
        zero_targets_counter += 1
        if zero_targets_counter > num_one_targets:
            indices_to_remove.append(i)

In [34]:
indices_to_remove

[563,
 564,
 565,
 566,
 567,
 568,
 574,
 575,
 578,
 582,
 583,
 584,
 586,
 588,
 589,
 590,
 592,
 593,
 594,
 595,
 597,
 598,
 601,
 602,
 603,
 605,
 606,
 610,
 611,
 613,
 614,
 616,
 617,
 619,
 620,
 623,
 624,
 625,
 626,
 628,
 629,
 631,
 633,
 634,
 636,
 637,
 638,
 639,
 640,
 642,
 646,
 648,
 650,
 652,
 654,
 655,
 656,
 657,
 658,
 659,
 661,
 662,
 663,
 665,
 666,
 667,
 668,
 671,
 672,
 674,
 675,
 676,
 678,
 680,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 693,
 694,
 695,
 696,
 698,
 699,
 702,
 703,
 704,
 705,
 711,
 713,
 714,
 715,
 718,
 719,
 721,
 722,
 723,
 725,
 728,
 729,
 731,
 732,
 733,
 734,
 735,
 736,
 738,
 739,
 741,
 743,
 745,
 746,
 748,
 749,
 752,
 753,
 756,
 757,
 758,
 760,
 761,
 764,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 775,
 776,
 778,
 782,
 783,
 784,
 785,
 787,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 798,
 799,
 800,
 805,
 806,
 807,
 808,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 822,
 824

In [35]:
np_inputs=inputs
np_inputs

Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
0         3    0  22.000000      1      0   7.2500         0
1         1    1  38.000000      1      0  71.2833         1
2         3    1  26.000000      0      0   7.9250         0
3         1    1  35.000000      1      0  53.1000         0
4         3    0  35.000000      0      0   8.0500         0
..      ...  ...        ...    ...    ...      ...       ...
886       2    0  27.000000      0      0  13.0000         0
887       1    1  19.000000      0      0  30.0000         0
888       3    1  29.699118      1      2  23.4500         0
889       1    0  26.000000      0      0  30.0000         1
890       3    0  32.000000      0      0   7.7500         2

[891 rows x 7 columns]

In [36]:
final_inputs=np_inputs.to_numpy()

In [37]:
type(final_inputs)

numpy.ndarray

In [38]:
unscaled_inputs=np.delete(final_inputs,indices_to_remove,axis=0)

In [39]:
unscaled_inputs

array([[ 3.    ,  0.    , 22.    , ...,  0.    ,  7.25  ,  0.    ],
       [ 1.    ,  1.    , 38.    , ...,  0.    , 71.2833,  1.    ],
       [ 3.    ,  1.    , 26.    , ...,  0.    ,  7.925 ,  0.    ],
       ...,
       [ 2.    ,  1.    , 25.    , ...,  1.    , 26.    ,  0.    ],
       [ 1.    ,  1.    , 19.    , ...,  0.    , 30.    ,  0.    ],
       [ 1.    ,  0.    , 26.    , ...,  0.    , 30.    ,  1.    ]])

In [40]:
new_targets=targets_all.to_numpy()

In [41]:
new_targets

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [42]:
final_targets=np.delete(new_targets,indices_to_remove,axis=0)

In [43]:
final_targets.shape

(684,)

In [44]:
unscaled_inputs.shape

(684, 7)

In [45]:
sum(final_targets)/final_targets.shape[0]
#The data is now balanced

0.5

In [46]:
#We will create a customer standardization
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin):
    def __init__(self,columns):
        self.scaler = StandardScaler()
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [47]:
cols=inputs.columns.values

In [48]:
df_inputs = pd.DataFrame(unscaled_inputs, columns = cols)
df_inputs

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3.0  0.0  22.0    1.0    0.0   7.2500       0.0
1       1.0  1.0  38.0    1.0    0.0  71.2833       1.0
2       3.0  1.0  26.0    0.0    0.0   7.9250       0.0
3       1.0  1.0  35.0    1.0    0.0  53.1000       0.0
4       3.0  0.0  35.0    0.0    0.0   8.0500       0.0
..      ...  ...   ...    ...    ...      ...       ...
679     3.0  1.0  15.0    0.0    0.0   7.2250       1.0
680     1.0  1.0  56.0    0.0    1.0  83.1583       1.0
681     2.0  1.0  25.0    0.0    1.0  26.0000       0.0
682     1.0  1.0  19.0    0.0    0.0  30.0000       0.0
683     1.0  0.0  26.0    0.0    0.0  30.0000       1.0

[684 rows x 7 columns]

In [49]:
df_targets=pd.DataFrame(final_targets,columns=['Survived'])
df_targets

Survived
0           0
1           1
2           1
3           1
4           0
..        ...
679         1
680         1
681         1
682         1
683         1

[684 rows x 1 columns]

In [50]:
Cols_to_scale=['Age','Fare']

In [51]:
scaler=CustomScaler(Cols_to_scale)

In [52]:
scaler.fit(df_inputs)

CustomScaler(columns=['Age', 'Fare'])

In [53]:
scaled_inputs=scaler.transform(df_inputs)

In [54]:
scaled_inputs

Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0       3.0  0.0 -0.561606    1.0    0.0 -0.532250       0.0
1       1.0  1.0  0.639401    1.0    0.0  0.631049       1.0
2       3.0  1.0 -0.261355    0.0    0.0 -0.519988       0.0
3       1.0  1.0  0.414212    1.0    0.0  0.300711       0.0
4       3.0  0.0  0.414212    0.0    0.0 -0.517717       0.0
..      ...  ...       ...    ...    ...       ...       ...
679     3.0  1.0 -1.087047    0.0    0.0 -0.532704       1.0
680     1.0  1.0  1.990534    0.0    1.0  0.846783       1.0
681     2.0  1.0 -0.336418    0.0    1.0 -0.191617       0.0
682     1.0  1.0 -0.786795    0.0    0.0 -0.118949       0.0
683     1.0  0.0 -0.261355    0.0    0.0 -0.118949       1.0

[684 rows x 7 columns]

In [55]:
scaled_inputs.shape

(684, 7)

In [56]:
df_targets.shape

(684, 1)

# We are done with preprocessing, now we will develop the model

In [57]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [58]:
x_train,x_test,y_train,y_test= train_test_split(scaled_inputs,df_targets, test_size=0.2, random_state=2)

In [59]:
model= LogisticRegression()
model.fit(x_train,y_train)

C:\Users\COMAP\Downloads\Anaconda\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [60]:
model.score(x_train,y_train)

0.7806215722120659

In [61]:
model_outputs=model.predict(x_train)
model_outputs

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,

In [62]:
final_targets

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [63]:
#The accuracy manually found
(np.sum(model_outputs==final_targets)/model_outputs.shape[0])

C:\Users\COMAP\AppData\Local\Temp/ipykernel_7328/3623213497.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  (np.sum(model_outputs==final_targets)/model_outputs.shape[0])


0.0

In [64]:
model.intercept_

array([1.12666969])

In [65]:
model.coef_

array([[-0.90807091,  2.41531084, -0.53207981, -0.44596085,  0.14708105,
         0.10764782,  0.29153124]])

In [66]:
feature_name=x_train.columns.values
feature_name

array(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'],
      dtype=object)

In [67]:
summary_table=pd.DataFrame(columns=['Feature name'],data=feature_name)
summary_table['Coefficients']=np.transpose(model.coef_)
summary_table

Feature name  Coefficients
0       Pclass     -0.908071
1          Sex      2.415311
2          Age     -0.532080
3        SibSp     -0.445961
4        Parch      0.147081
5         Fare      0.107648
6     Embarked      0.291531

In [68]:
summary_table.index=summary_table.index+1
summary_table.loc[0]=['Intercept',model.intercept_[0]]

In [69]:
summary_table.sort_index()

Feature name  Coefficients
0    Intercept      1.126670
1       Pclass     -0.908071
2          Sex      2.415311
3          Age     -0.532080
4        SibSp     -0.445961
5        Parch      0.147081
6         Fare      0.107648
7     Embarked      0.291531

In [70]:
summary_table['Odds Ratio']=np.exp(summary_table.Coefficients)
summary_table= summary_table.sort_index()
summary_table.sort_values('Odds Ratio',ascending= False)

Feature name  Coefficients  Odds Ratio
2          Sex      2.415311   11.193249
0    Intercept      1.126670    3.085364
7     Embarked      0.291531    1.338475
5        Parch      0.147081    1.158448
6         Fare      0.107648    1.113655
4        SibSp     -0.445961    0.640209
3          Age     -0.532080    0.587382
1       Pclass     -0.908071    0.403301

# Testing the model

In [71]:
model.score(x_test,y_test)

0.781021897810219

In [72]:
pred_outcome=model.predict(x_test)
pred_outcome

array([0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0], dtype=int64)

In [73]:
numpy_y=y_test.to_numpy(dtype = None, copy = False)
numpy_y

array([[1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
    

In [74]:
numpy_y.shape

(137, 1)

In [75]:
pred_outcome.shape

(137,)

In [76]:
from sklearn.metrics import confusion_matrix

In [77]:
a=confusion_matrix(numpy_y,pred_outcome)
a

array([[50, 14],
       [16, 57]], dtype=int64)

In [78]:
#Thus, the confusion matrix also shows around 78% accuracy

# Finally, we have to make predictions for the test data given

In [79]:
test_data

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [80]:
prediction_data=test_data.copy()

In [81]:
prediction_data=prediction_data.drop(['PassengerId','Name','Ticket','Cabin'],axis=1)
prediction_data

Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0         3    male  34.5      0      0    7.8292        Q
1         3  female  47.0      1      0    7.0000        S
2         2    male  62.0      0      0    9.6875        Q
3         3    male  27.0      0      0    8.6625        S
4         3  female  22.0      1      1   12.2875        S
..      ...     ...   ...    ...    ...       ...      ...
413       3    male   NaN      0      0    8.0500        S
414       1  female  39.0      0      0  108.9000        C
415       3    male  38.5      0      0    7.2500        S
416       3    male   NaN      0      0    8.0500        S
417       3    male   NaN      1      1   22.3583        C

[418 rows x 7 columns]

In [82]:
prediction_data.replace({'Sex':{'male':0,'female':1}, 'Embarked':{'S':0,'C':1,'Q':2}}, inplace=True)
prediction_data.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    0  34.5      0      0   7.8292         2
1       3    1  47.0      1      0   7.0000         0
2       2    0  62.0      0      0   9.6875         2
3       3    0  27.0      0      0   8.6625         0
4       3    1  22.0      1      1  12.2875         0

In [83]:
prediction_data['Age'].fillna(prediction_data['Age'].mean(), inplace=True)

In [84]:
prediction_data['Fare'].fillna(prediction_data['Fare'].mean(), inplace=True)

In [85]:
prediction_data.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [86]:
scaler.fit(prediction_data)
scaled_inputs_prediction=scaler.transform(prediction_data)
scaled_inputs_prediction

Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0         3    0  0.334993      0      0 -0.498407         2
1         3    1  1.325530      1      0 -0.513274         0
2         2    0  2.514175      0      0 -0.465088         2
3         3    0 -0.259330      0      0 -0.483466         0
4         3    1 -0.655545      1      1 -0.418471         0
..      ...  ...       ...    ...    ...       ...       ...
413       3    0  0.000000      0      0 -0.494448         0
414       1    1  0.691586      0      0  1.313753         1
415       3    0  0.651965      0      0 -0.508792         0
416       3    0  0.000000      0      0 -0.494448         0
417       3    0  0.000000      1      1 -0.237906         1

[418 rows x 7 columns]

In [87]:
final_survival_predictions=model.predict(scaled_inputs_prediction)
final_survival_predictions

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,

In [88]:
predicted_prob=model.predict_proba(scaled_inputs_prediction)
predicted_prob

array([[0.77667186, 0.22332814],
       [0.59597782, 0.40402218],
       [0.8167104 , 0.1832896 ],
       [0.81929864, 0.18070136],
       [0.30520299, 0.69479701],
       [0.72360017, 0.27639983],
       [0.20451914, 0.79548086],
       [0.69444755, 0.30555245],
       [0.17193928, 0.82806072],
       [0.89289419, 0.10710581],
       [0.8390352 , 0.1609648 ],
       [0.6137509 , 0.3862491 ],
       [0.07013578, 0.92986422],
       [0.92648576, 0.07351424],
       [0.17770557, 0.82229443],
       [0.139359  , 0.860641  ],
       [0.5867779 , 0.4132221 ],
       [0.72509251, 0.27490749],
       [0.38785833, 0.61214167],
       [0.39328613, 0.60671387],
       [0.7175911 , 0.2824089 ],
       [0.64934847, 0.35065153],
       [0.06746501, 0.93253499],
       [0.25013726, 0.74986274],
       [0.06843931, 0.93156069],
       [0.94863464, 0.05136536],
       [0.03011408, 0.96988592],
       [0.73751839, 0.26248161],
       [0.56060143, 0.43939857],
       [0.90245934, 0.09754066],
       [0.

In [89]:
predicted_survival_prob=predicted_prob[:,1]

In [90]:
df_predictions= pd.DataFrame(final_survival_predictions,columns=['Prediction'])
df_predictions

Prediction
0             0
1             0
2             0
3             0
4             1
..          ...
413           0
414           1
415           0
416           0
417           0

[418 rows x 1 columns]

In [91]:
test_data['Prediction']=df_predictions

In [92]:
test_data

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  \
0      male  34.5      0      0              330911    7.8292   NaN        Q   
1    female  47.0      1      0              363272    7.0000   NaN        S   
2      male  62.0      0      0              240276    9.6875   NaN        Q   
3      male  27.0      0      0              315154    8.6625   NaN        S   
4    female  22.0      1      1             3101298   12.2875   NaN        S   
..      ...   ...    ...    ...                 ...       ...   ...      ...   
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S   
414  female  39.0      0      0            PC 17758  108.9000  C105        C   
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S   
416    male   NaN      0      0              359309    8.0500   NaN        S   
417    male   NaN      1      1                2668   22.3583   NaN        C   

     Prediction  
0             0  
1             0  
2             0  
3             0  
4             1  
..          ...  
413           0  
414           1  
415           0  
416           0  
417           0  

[418 rows x 12 columns]

In [93]:
sum(test_data['Prediction'])

177

In [94]:
df_surv_prob= pd.DataFrame(predicted_survival_prob,columns=['Survival probability'])
df_surv_prob

Survival probability
0                0.223328
1                0.404022
2                0.183290
3                0.180701
4                0.694797
..                    ...
413              0.161005
414              0.936961
415              0.119286
416              0.161005
417              0.163762

[418 rows x 1 columns]

In [95]:
test_data['Survival probability']=df_surv_prob

In [96]:
test_data

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  \
0      male  34.5      0      0              330911    7.8292   NaN        Q   
1    female  47.0      1      0              363272    7.0000   NaN        S   
2      male  62.0      0      0              240276    9.6875   NaN        Q   
3      male  27.0      0      0              315154    8.6625   NaN        S   
4    female  22.0      1      1             3101298   12.2875   NaN        S   
..      ...   ...    ...    ...                 ...       ...   ...      ...   
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S   
414  female  39.0      0      0            PC 17758  108.9000  C105        C   
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S   
416    male   NaN      0      0              359309    8.0500   NaN        S   
417    male   NaN      1      1                2668   22.3583   NaN        C   

     Prediction  Survival probability  
0             0              0.223328  
1             0              0.404022  
2             0              0.183290  
3             0              0.180701  
4             1              0.694797  
..          ...                   ...  
413           0              0.161005  
414           1              0.936961  
415           0              0.119286  
416           0              0.161005  
417           0              0.163762  

[418 rows x 13 columns]

In [97]:
test_data.to_csv('Prediction data.csv',index=False)